name: Concept CI

on:
  push:
    branches-ignore:
      - master
    paths:
      - 'languages/common-lisp/config.json'
      - 'languages/common-lisp/reference/concepts.csv'
      - 'languages/common-lisp/reference/exercise-concepts/**'
      - 'languages/common-lisp/exercises/concept/**'
  pull_request:
    paths:
      - 'languages/common-lisp/config.json'
      - 'languages/common-lisp/reference/concepts.csv'
      - 'languages/common-lisp/reference/exercise-concepts/**'
      - 'languages/common-lisp/exercises/concept/**'
  schedule:
    # To prevent sysimage cache from expiring after not being accessed for 7 days, run the workflow every 6 days.
    # Due to the long time needed to build the sysimage, this should overall save time.
    - cron: 13 7 */6 * *

jobs:
  concept-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Fetch everything
        run: git fetch --prune --unshallow

      - name: Detect track
        id: track-detection
        run: |
          TRACK=$(git diff --name-only origin/master... | grep -oP 'languages\/\K([a-z0-9-]+)' | head -1)
          # default fallback for scheduled builds
          [ -z "$TRACK" ] && TRACK="julia"
          case "$TRACK" in
            common-lisp) OPTS="--no-extraction-check --no-directory-check" ;;
          esac
          echo "::set-output name=track::$TRACK"
          echo "::set-output name=opts::$OPTS"
        shell: bash

      - name: Install dependencies
        run: julia --color=yes --project=.github/bin/concept-checks -e "using Pkg; Pkg.instantiate()"

      - name: Cache sysimage
        id: sysimage-cache
        uses: actions/cache@v1
        with:
          path: julia-sysimages
          key: ${{ runner.os }}-concept-checks-sysimage-${{ hashFiles('.github/bin/concept-checks/Manifest.toml') }}-${{ hashFiles('.github/bin/concept-checks/concept-checks.jl') }}

      - name: Build sysimage (this might take a while)
        if: steps.sysimage-cache.outputs.cache-hit != 'true'
        run: |
          mkdir("julia-sysimages")
          using PackageCompiler
          cd(joinpath("languages", "julia"))
          # explanation for cpu_target: https://github.com/JuliaLang/PackageCompilerX.jl/issues/106
          create_sysimage([:ArgParse, :CSV, :JSON], sysimage_path=joinpath("${{ github.workspace }}", "julia-sysimages", "sysimage-concept-checks.so"), precompile_execution_file="${{ github.workspace }}/.github/bin/concept-checks/concept-checks.jl"; cpu_target="generic")
        shell: bash -c "julia --color=yes --project=.github/bin/concept-checks {0}"

      - name: Run concept checks
        continue-on-error: true
        run: |
          julia --sysimage=julia-sysimages/sysimage-concept-checks.so --color=yes --project=.github/bin/concept-checks .github/bin/concept-checks/concept-checks.jl -r . -t ${{ steps.track-detection.outputs.track }} ${{ steps.track-detection.outputs.opts }}
