name: Julia config CI

on:
  push:
    paths:
    - 'languages/julia/config.json'
    - 'languages/julia/concepts.csv'
  pull_request:
    paths:
    - 'languages/julia/config.json'
    - 'languages/julia/concepts.csv'

jobs:
  config-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
      
      - name: Install dependencies
        run: |
          cd languages/julia/
          julia --color=yes --project=bin -e "using Pkg; Pkg.instantiate()"

      - name: Run concept checks
        run: |
          cd languages/julia/
          julia --color=yes --project=bin bin/concept-checks.jl
