name: CI

on:
  push:
  pull_request:

jobs:
  verify-code-formatting:
    name: Verify formatting
    runs-on: [ubuntu-latest]
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v2

      - name: 'Verify formatting of all files'
        if: github.ref == 'refs/heads/master'
        run: npx prettier@2.1.2 --check "**/*.{js,jsx,ts,tsx,css,sass,scss,html,json,md,yml}"

      - name: "Verify formatting of the PR's files"
        if: github.ref != 'refs/heads/master' && github.event.pull_request.url
        run: |
          PULL_REQUEST_URL=$(jq -r ".pull_request.url" "$GITHUB_EVENT_PATH")
          curl --url $"${PULL_REQUEST_URL}/files" --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | \
            jq -c '.[] | select(.status == "added" or .status == "modified") | select(.filename | match("\\.(js,jsx,ts,tsx,css,sass,scss,html,json,md,yml)$")) | .filename' | \
            xargs -r npx prettier@2.1.2 --check
